"""AceStepConditioningSplitter node for ACE-Step"""
import torch

class AceStepConditioningSplitter:
    """Deconstructs a full ACE-Step conditioning object into its isolated, mutable components.
    
    This node intercepts the raw mathematical tensors generated by the text encoder before 
    they hit the DiT sampler, allowing for complex audio algebra and modular replacement.
    
    Inputs:
        conditioning (CONDITIONING): The standard ComfyUI formatting bundle.
        
    Outputs:
        timbre_tensor (TENSOR): The base conditioning tensor representing overall audio style.
        pooled_output (TENSOR): The pooled sequence output.
        lyrics_tensor (TENSOR): The vocal guidance/timing tensor (if present).
        audio_codes (LIST): The 5Hz prompt token IDs driving structural generation.
    """
    
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "conditioning": ("CONDITIONING",),
            }
        }
    
    RETURN_TYPES = ("TENSOR", "TENSOR", "TENSOR", "LIST")
    RETURN_NAMES = ("timbre_tensor", "pooled_output", "lyrics_tensor", "audio_codes")
    FUNCTION = "split"
    CATEGORY = "Scromfy/Ace-Step/Conditioning"

    def split(self, conditioning):
        if not conditioning or len(conditioning) == 0:
            return (None, None, None, None)
            
        # We take the first item in the conditioning list (standard for ACE-Step)
        # Note: If there are multiple items, this node follows the pattern of only processing the first.
        item = conditioning[0]
        timbre_tensor = item[0]
        metadata = item[1]
        
        pooled_output = metadata.get("pooled_output")
        lyrics_tensor = metadata.get("conditioning_lyrics")
        audio_codes = metadata.get("audio_codes")
        
        return (timbre_tensor, pooled_output, lyrics_tensor, audio_codes)

NODE_CLASS_MAPPINGS = {
    "AceStepConditioningSplitter": AceStepConditioningSplitter,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AceStepConditioningSplitter": "Conditioning Component Splitter",
}
