"""Prompt generation utilities and presets for ACE-Step"""

STYLE_PRESETS = {
    "Synthwave": "Synthwave with vintage analog synths, lo-fi drums, neon pad atmospheres, retro 80s aesthetic",
    "Retrowave": "Retrowave with analog synth layers, pulsing bassline, 80s drum kit samples, warm pad chords",
    "Electronic": "Electronic dance with punchy sidechain kick, filtered saw bass, lush pad atmospheres, crisp hi-hats",
    "Trance": "Trance with arpeggiated synth lines, hypnotic bassline, breakbeat patterns, euphoric builds",
    "Techno": "Minimal techno with repetitive kick patterns, industrial percussion, deep sub bass, subtle synth layers",
    "House": "Deep house with soulful samples, warm bassline, jazzy chords, vocal intimacy",
    "Dubstep": "Dubstep with heavy wobble bass, syncopated snares, dub-influenced delays, explosive drops",
    "Trap": "Trap with booming 808 sub bass slides, rapid hi-hat rolls, sparse atmospheric synth melodies, snare snaps",
    "Future Bass": "Future bass with chopped vocals, complex chords, soft wobble bass, glitchy rhythms, emotional melodic content",
    "Lo-fi Hip Hop": "Lo-fi hip hop with vinyl crackle, jazzy piano chords, dusty drum samples, warm bass, chill vibes",
    "Ambient": "Ambient music with flowing pad textures, minimalist melodies, atmospheric soundscapes, meditative space",
    "Vaporwave": "Vaporwave with ambient samples, lo-fi aesthetics, slowed jazz, consumer culture samples, nostalgic melancholy",
    "Cyberpunk": "Cyberpunk electronic with futuristic synths, distorted vocals, heavy bass, neon aesthetics, dystopian atmosphere",
    "Rock": "Rock with power chords, driving drums, electric guitar solos, punchy bass",
    "Metal": "Metal with heavy distorted guitars, double bass drums, aggressive vocals, intense energy",
    "Punk": "Punk with fast power chords, raw shouted vocals, simple drums, rebellious energy",
    "Jazz": "Jazz with swing rhythms, saxophone solos, walking bass, piano comping, brushed drums",
    "Blues": "Blues with guitar bends, walking upright bass, brushed snare, harmonica wails",
    "Country": "Country with acoustic guitar, steel guitar slides, fiddle, storytelling vocals",
    "Pop": "Pop with catchy hooks, electronic production, polished vocals, dance beats",
}

GENRES = [
    "rock",
    "ambient",
    "avant-garde",
    "blues",
    "children's",
    "chillwave",
    "christian",
    "classical",
    "country",
    "dance",
    "dubstep",
    "edm",
    "electronic",
    "experimental",
    "folk",
    "funk",
    "hiphop",
    "house",
    "indie",
    "jazz",
    "latin",
    "lo-fi",
    "metal",
    "oldies",
    "pop",
    "punk",
    "r&b",
    "rap",
    "reggae",
    "religious",
    "soul",
    "soundtrack",
    "synthwave",
    "techno",
    "trance",
    "trap",
    "world"
]

MOODS = [
    "energetic",
    "mellow",
    "dark",
    "uplifting",
    "emotional",
    "atmospheric",
    "driving",
    "intense",
    "calm",
    "mysterious",
    "nostalgic",
    "futuristic",
    "dreamy",
    "aggressive",
    "peaceful"
]

ADJECTIVES = [
    "abstract",
    "acid",
    "acoustic",
    "21st century",
    "christian",
    "dark",
    "deep",
    "experimental",
    "melodic",
    "minimal",
    "modern",
    "progressive",
    "vintage",
    "traditional",
    "technical",
    "symphonic",
    "post-",
    "old school",
    "gothic"
]   

CULTURES = [
    "aarhus",
    "aberdeen",
    "adelaide",
    "afghan",
    "african",
    "afrikaans",
    "afro",
    "alabama",
    "alaska",
    "albanian",
    "alberta",
    "albuquerque",
    "appalachian",
    "arab",
    "argentine",
    "arkansas",
    "armenian",
    "athens",
    "aussie",
    "australian",
    "austrian",
    "balkan",
    "baltic",
    "baltimore",
    "belfast",
    "belgian",
    "boston",
    "brazilian",
    "british",
    "bulgarian",
    "canadian",
    "celtic",
    "chicago",
    "chilean",
    "chinese",
    "colombian",
    "croatian",
    "cuban",
    "czech",
    "danish",
    "detroit",
    "dutch",
    "ecuadorian",
    "edinburgh",
    "estonian",
    "finnish",
    "french",
    "german",
    "ghanaian",
    "greek",
    "guatemalan",
    "hamburg",
    "hawaiian",
    "hungarian",
    "icelandic",
    "indian",
    "indonesian",
    "irish",
    "israeli",
    "italian",
    "japanese",
    "korean",
    "latin",
    "latvian",
    "lithuanian",
    "luxembourgian",
    "macedonian",
    "malaysian",
    "memphis",
    "mexican",
    "miami",
    "nashville",
    "native american",
    "nordic",
    "norwegian",
    "nz",
    "pakistani",
    "palestinian",
    "panamanian",
    "persian",
    "peruvian",
    "pinoy",
    "polish",
    "portuguese",
    "psychedelic",
    "puerto rican",
    "punjabi",
    "quebec",
    "romanian",
    "russian",
    "scandinavian",
    "scottish",
    "singaporean",
    "slovak",
    "slovenian",
    "spanish",
    "swedish",
    "swiss",
    "taiwanese",
    "texas",
    "thai",
    "toronto",
    "turkish",
    "uk",
    "ukrainian",
    "vancouver",
    "venezuelan",
    "vietnamese",
    "virgin islands",
    "washington",
    "wellington",
    "welsh",
    "west virginia",
    "western mass",
    "western saharan",
    "windsor",
    "winnipeg",
    "wisconsin",
    "wyoming",
    "york",
    "yugoslav",
    "zambian",
    "zurich"
]

INSTRUMENTS = [
    "synthesizer",
    "guitar",
    "piano",
    "drums",
    "bass",
    "strings",
    "brass",
    "saxophone",
    "violin",
    "organ",
    "808 drums",
    "analog synth",
    "electric guitar",
    "acoustic guitar"
]

PERFORMERS = [
    "solo",
    "duo",
    "trio",
    "quartet",
    "quintet",
    "choir",
    "orchestra",
    "band",
    "ensemble"
]

VOCAL_QUALITIES = [
    "male",
    "female",
    "child",
    "adult",
    "old",
    "young",
    "deep",
    "high",
    "soft",
    "loud",
    "clear",
    "raspy",
    "breathy",
    "powerful",
    "delicate",
    "energetic",
    "calm",
    "mysterious",
    "nostalgic",
    "futuristic",
    "dreamy",
    "aggressive",
    "peaceful"
]
